// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo0JRz1HKlQRcHVUiRSQhSZb0UYr_zxOs',
    appId: '1:56869221874:android:fd8892240c8e9c3121a76b',
    messagingSenderId: '56869221874',
    projectId: 'calorie-tracker-6e32c',
    storageBucket: 'calorie-tracker-6e32c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8vebFRBbio3zloQ1YWeFlou5B58qUTHY',
    appId: '1:56869221874:ios:5ed6816d1bf4acf921a76b',
    messagingSenderId: '56869221874',
    projectId: 'calorie-tracker-6e32c',
    storageBucket: 'calorie-tracker-6e32c.firebasestorage.app',
    iosBundleId: 'com.example.calorieTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8vebFRBbio3zloQ1YWeFlou5B58qUTHY',
    appId: '1:56869221874:ios:5ed6816d1bf4acf921a76b',
    messagingSenderId: '56869221874',
    projectId: 'calorie-tracker-6e32c',
    storageBucket: 'calorie-tracker-6e32c.firebasestorage.app',
    iosBundleId: 'com.example.calorieTracker',
  );
}
